apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: load-gen-hpa
  namespace: amit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-gen-depl
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50